version: '3'
services:
  ncanteen-api:
    image: dfanso/ncanteen-api
    container_name: ncanteen-api
    ports:
      - "3000:3000" 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER: dfanso
    command: ["node", "index.js"]
    restart: always 
    networks:
      - my-network
    env_file:
      - ./.env

networks:
  my-network:


